### ISSUE TITLE
When building in parallel, I get a warning...

### ISSUE THREAD

**Issue by FredM67** [AaltoSciComp/sphinx_rtd_theme_ext_color_contrast#6]
```
WARNING: the sphinx_rtd_theme_ext_color_contrast extension does not declare if it is safe for parallel reading, assuming it isn't - please ask the extension author to check and make it explicit
WARNING: doing serial read
```

Could you please declare it safe or unsafe ?
Thx

**Comment by rkdarst** [comment]
Oh, good to know.  I wonder why it doesn't do that, I've know how to do that for Sphinx extensions forever.

I just made a release.  Can you let me know if everything works ok?  (I did a basic test but it's not all that well tested).

**Comment by FredM67** [comment]
Hm... same warning !
pip list says `sphinx-rtd-theme-ext-color-contrast 0.3.1`.

**Comment by FredM67** [comment]
The warning is still present ?
Any news ?
Thx

**Comment by FredM67** [comment]
I think, the reason is that the return is "inside" the `else`.
The indentation is wrong.

**Comment by rkdarst** [comment]
That was an embarrassing mistake.  Thanks for finding and fixing it.

I've made a new release now - I hope it works now?

**Comment by FredM67** [comment]
> That was an embarrassing mistake. Thanks for finding and fixing it.
> 
> I've made a new release now - I hope it works now?

Well I must say, that the typical trivial error nobody'll ever see ! Except you leave the code for a while, so everything is "gone" from your brain, and then check again !

Thx for the very fast reaction !

**Comment by FredM67** [comment]
Warning is gone ! Great !
